name: Update News Popularity (Using Pre-Built Docker Image)

on:
  schedule:
    - cron: '0 */4 * * *'  # 每 4 小時運行一次
  workflow_dispatch:  # 允許手動觸發
  push:
    branches:
      - main

jobs:
  run-popularity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Timezone
        run: sudo timedatectl set-timezone Asia/Taipei

      - name: Test Google Trends API Connectivity
        run: |
          docker run --rm rollin2000tw/google-trends-scraper bash -c "wget -S --spider https://trends.google.com/trends/api/explore"

      - name: Verify Playwright Installation
        run: |
          docker run --rm rollin2000tw/google-trends-scraper bash -c "ls -lah /root/.cache/ms-playwright"

      - name: Ensure Output Directory Exists
        run: mkdir -p $(pwd)/app/output

      - name: Pull Latest Docker Image
        run: docker pull --platform=linux/amd64 rollin2000tw/google-trends-scraper:latest

      - name: Run Google Trends Scraper
        run: |
          docker run --rm \
            -v $(pwd)/app/output:/app/output \
            rollin2000tw/google-trends-scraper:latest \
            python google_trends_scraper.py

      - name: Check Output Directory Content
        run: ls -lah $(pwd)/app/output

      - name: Show Trending Keywords JSON
        run: cat $(pwd)/app/output/trending_keywords.json || echo "No data found."

      - name: Run Popularity Calculation
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          docker run --rm \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            -v $(pwd)/app/output:/app/output \
            rollin2000tw/google-trends-scraper:latest \
            python set_popularity.py
