name: Update News Popularity (Using Pre-Built Docker Image)

on:
  schedule:
    - cron: '0 */4 * * *'  # 每 4 小時運行一次
  workflow_dispatch:  # 允許手動觸發
  push:
    branches:
      - main  # 只有 main 分支的變更才會觸發

jobs:
  run-popularity:
    runs-on: ubuntu-latest  # GitHub Actions 預設是 AMD64

    steps:
      # 1. (可選) 檢出原始碼，如果只想單純 pull docker image 來跑，可以省略
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Pull & Run Google Trends Scraper
      - name: Pull and Run Google Trends Scraper
        run: |
          docker pull --platform=linux/amd64 rollin2000tw/google-trends-scraper:latest
          docker run --rm \
            -v $(pwd)/app/output:/app/output \
            rollin2000tw/google-trends-scraper:latest \
            python google_trends_scraper.py

      # 3. Pull & Run Popularity Calculation
      - name: Run Popularity Calculation
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          docker pull --platform=linux/amd64 rollin2000tw/google-trends-scraper:latest
          docker run --rm \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            -v $(pwd)/app/output:/app/output \
            rollin2000tw/google-trends-scraper:latest \
            python set_popularity.py
