name: Update News Popularity (Using Pre-Built Docker Image)

on:
  schedule:
    - cron: '0 */4 * * *'  # 每 4 小時運行一次
  workflow_dispatch:  # 允許手動觸發
  push:
    branches:
      - main  # 只有 main 分支的變更才會觸發

jobs:
  run-popularity:
    runs-on: ubuntu-latest  # GitHub Actions 預設是 x86_64

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 確保使用最新的 Docker 映像
      - name: Pull Latest Docker Image
        run: |
          echo "[Run] Pulling the latest docker image..."
          docker pull --platform=linux/amd64 rollin2000tw/google-trends-scraper:latest

      # 執行 Google Trends 爬蟲
      - name: Run Google Trends Scraper
        run: |
          echo "[Run] Executing google_trends_scraper.py in container..."
          docker run --rm \
            -v $(pwd)/app/output:/app/output \
            rollin2000tw/google-trends-scraper:latest \
            python google_trends_scraper.py

      # 執行 Popularity Calculation
      - name: Run Popularity Calculation
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          echo "[Run] Executing set_popularity.py with database connection..."
          docker run --rm \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            -v $(pwd)/app/output:/app/output \
            rollin2000tw/google-trends-scraper:latest \
            python set_popularity.py
