name: Update News Popularity (Using Pre-Built Docker Image)

on:
  schedule:
    - cron: '0 */4 * * *'  # 每 4 小時運行一次
  workflow_dispatch:  # 允許手動觸發
  push:
    branches:
      - main  # 只有 main 分支的變更才會觸發

jobs:
  run-popularity:
    runs-on: ubuntu-latest  # GitHub Actions 預設是 AMD64

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 檢查 Playwright 是否已安裝
      - name: Check Playwright Installation
        run: |
          docker run --rm rollin2000tw/google-trends-scraper \
            bash -c "playwright --version"

      # 安裝 Playwright 瀏覽器
      - name: Install Playwright Browsers
        run: |
          docker run --rm rollin2000tw/google-trends-scraper \
            bash -c "playwright install --with-deps chromium"

      # 測試 Playwright 是否能開啟 Google
      - name: Test Playwright Headless Chromium (Using Python)
        run: |
          docker run --rm rollin2000tw/google-trends-scraper python -c \
            "from playwright.sync_api import sync_playwright; p = sync_playwright().start(); b = p.chromium.launch(headless=True); print('Success'); b.close()"

      # 測試 Google Trends 是否可以被訪問
      - name: Check Google Trends Access
        run: |
          docker run --rm rollin2000tw/google-trends-scraper \
            bash -c "wget -S --spider https://trends.google.com/trends/api/explore"

      # 執行爬蟲
      - name: Pull and Run Google Trends Scraper
        run: |
          docker pull --platform=linux/amd64 rollin2000tw/google-trends-scraper:latest
          docker run --rm \
            -v $(pwd)/app/output:/app/output \
            rollin2000tw/google-trends-scraper:latest \
            python google_trends_scraper.py

      # 執行 Popularity Calculation
      - name: Run Popularity Calculation
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          docker pull --platform=linux/amd64 rollin2000tw/google-trends-scraper:latest
          docker run --rm \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            -v $(pwd)/app/output:/app/output \
            rollin2000tw/google-trends-scraper:latest \
            python set_popularity.py
